from langchain_ollama import OllamaLLM

from rag.context_validator import validate_context_for_question
from rag.retrieval import retrieve_relevant_documents
from rag.prompts import SYSTEM_PROMPT
from rag.kb_answer import answer_from_kb


FALLBACK_ANSWER = (
    "Sorry, I could not find official information about this."
)

SPECIFIC_PROGRAM_FALLBACK = (
    "Sorry, I could not find official information about this specific program."
)


llm = OllamaLLM(
    model="iub-rag-fast",
    temperature=0,
    keep_alive="30m",
)


def build_context(retrieved_docs):
    context_parts = []

    for index, doc in enumerate(retrieved_docs, start=1):
        category = doc["metadata"].get("category", "unknown")
        content = doc.get("content", "")

        context_parts.append(
            f"Document {index}\n"
            f"Category: {category}\n"
            f"Content:\n{content}"
        )

    return "\n\n---\n\n".join(context_parts)


def build_sources(retrieved_docs):
    sources = []

    for doc in retrieved_docs:
        source_info = {
            "source": doc["metadata"].get("source"),
            "category": doc["metadata"].get("category"),
            "score": doc.get("score"),
        }

        if source_info not in sources:
            sources.append(source_info)

    return sources


def clean_answer(answer):
    if not answer:
        return FALLBACK_ANSWER

    answer = str(answer).strip()

    if not answer:
        return FALLBACK_ANSWER

    return answer


def ask_chatbot(question: str):
    question = question.strip()

    if not question:
        return {
            "answer": "Please enter a valid question.",
            "sources": [],
        }

    retrieved_docs = retrieve_relevant_documents(question, k=5)

    if not retrieved_docs:
        return {
            "answer": FALLBACK_ANSWER,
            "sources": [],
        }

    sources = build_sources(retrieved_docs)

    if not validate_context_for_question(question, retrieved_docs):
        return {
            "answer": SPECIFIC_PROGRAM_FALLBACK,
            "sources": sources,
        }

    context = build_context(retrieved_docs)

    prompt = SYSTEM_PROMPT.format(
        context=context,
        question=question,
    )

    answer = llm.invoke(prompt)
    answer = clean_answer(answer)

    return {
        "answer": answer,
        "sources": sources,
    }


def print_sources(sources):
    print("\nSources:")

    unique_sources = []

    for source in sources:
        source_key = (source.get("source"), source.get("category"))

        if source_key not in unique_sources:
            unique_sources.append(source_key)

            score = source.get("score")
            if isinstance(score, (int, float)):
                score_text = round(score, 4)
            else:
                score_text = score if score is not None else "N/A"

            print(
                f"- {source.get('source')} | "
                f"Category: {source.get('category')} | "
                f"Score: {score_text}"
            )


def main():
    print("IUB Offline RAG Chatbot")
    print("Type 'exit' to stop.\n")

    last_question = ""

    while True:
        question = input("You: ").strip()

        if question.lower() in ["exit", "quit", "bye"]:
            print("Chatbot closed.")
            break

        if not question:
            print("Please enter a question.")
            continue

        # Data-driven KB answer first. No university facts are hardcoded here;
        # data comes from app/knowledge_base generated by scripts/build_knowledge_base.py.
        result = answer_from_kb(question, last_question)

        if result is None:
            result = ask_chatbot(question)

        print("\nBot:")
        print(result["answer"])

        print_sources(result.get("sources", []))

        last_question = question

        print("\n" + "-" * 60 + "\n")


if __name__ == "__main__":
    main()
